### ISSUE TITLE
[go vendor] generator chokes on => lines

### ISSUE THREAD

**Issue by muelli** [flatpak/flatpak-builder-tools#119]
I know next to nothing about Go, let alone managing dependencies. When packaging syncthing, I noticed that the line

`# github.com/spaolacci/murmur3 v1.1.0 => github.com/twmb/murmur3 v1.1.3`

makes it barf:
```
Traceback (most recent call last):
  File "/home/muelli/vcs/flatpak-builder-tools/go-get/flatpak-go-vendor-generator.py", line 92, in <module>
    main()
  File "/home/muelli/vcs/flatpak-builder-tools/go-get/flatpak-go-vendor-generator.py", line 88, in main
    fp_modules = [go_module_to_flatpak(m) for m in parse_modules(fh)]
  File "/home/muelli/vcs/flatpak-builder-tools/go-get/flatpak-go-vendor-generator.py", line 88, in <listcomp>
    fp_modules = [go_module_to_flatpak(m) for m in parse_modules(fh)]
  File "/home/muelli/vcs/flatpak-builder-tools/go-get/flatpak-go-vendor-generator.py", line 44, in parse_modules
    _, name, version = line.split(" ")
ValueError: too many values to unpack (expected 3)
```

I guess it's coming from here:
https://github.com/syncthing/syncthing/blob/ebad9e20732d4e924f06e1d4c2066ad07a83afb4/go.mod#L55

**Comment by bbhtt** [comment]
Seems like it was fixed by https://github.com/flatpak/flatpak-builder-tools/pull/120
