### ISSUE TITLE
[pip] error: pip._vendor.pep517.wrappers.BackendUnavailable

### ISSUE THREAD

**Issue by roipoussiere** [flatpak/flatpak-builder-tools#122]
When ruuning the command `python fp_pip.py qtconsole`, I get the error `pip._vendor.pep517.wrappers.BackendUnavailable`.

## Full stacktrace

<details><summary>click to expand</summary><pre>
Looking in indexes: https://pypi.org/simple
Collecting qtconsole
  Using cached https://files.pythonhosted.org/packages/61/9c/ee26b844381f0cf2ea24bd822e4a9ed2c7fd6d8cdeef63be459c62132f9b/qtconsole-4.7.4-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/qtconsole-4.7.4-py2.py3-none-any.whl
Collecting pygments (from qtconsole)
  Using cached https://files.pythonhosted.org/packages/2d/68/106af3ae51daf807e9cdcba6a90e518954eb8b70341cee52995540a53ead/Pygments-2.6.1-py3-none-any.whl
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/Pygments-2.6.1-py3-none-any.whl
Collecting jupyter-core (from qtconsole)
  Using cached https://files.pythonhosted.org/packages/63/0d/df2d17cdf389cea83e2efa9a4d32f7d527ba78667e0153a8e676e957b2f7/jupyter_core-4.6.3-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/jupyter_core-4.6.3-py2.py3-none-any.whl
Collecting qtpy (from qtconsole)
  Using cached https://files.pythonhosted.org/packages/cd/fd/9972948f02e967b691cc0ca1f26124826a3b88cb38f412a8b7935b8c3c72/QtPy-1.9.0-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/QtPy-1.9.0-py2.py3-none-any.whl
Collecting ipython-genutils (from qtconsole)
  Using cached https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting ipykernel>=4.1 (from qtconsole)
  Using cached https://files.pythonhosted.org/packages/ed/5d/cf47741fa80826f8edf435d9bcf0e84eef2d6d02953ff85e0563b3ab3f0b/ipykernel-5.2.1-py3-none-any.whl
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/ipykernel-5.2.1-py3-none-any.whl
Collecting traitlets (from qtconsole)
  Using cached https://files.pythonhosted.org/packages/ca/ab/872a23e29cec3cf2594af7e857f18b687ad21039c1f9b922fac5b9b142d5/traitlets-4.3.3-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/traitlets-4.3.3-py2.py3-none-any.whl
Collecting jupyter-client>=4.1 (from qtconsole)
  Using cached https://files.pythonhosted.org/packages/34/0b/2ebddf775f558158ca8df23b35445fb15d4b1558a9e4a03bc7e75b13476e/jupyter_client-6.1.3-py3-none-any.whl
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/jupyter_client-6.1.3-py3-none-any.whl
Collecting pyzmq>=17.1 (from qtconsole)
  Using cached https://files.pythonhosted.org/packages/43/93/36a783239874b894d1fe1e791185ee6e627529661190bb06dc9f16fca78f/pyzmq-19.0.1-cp37-cp37m-manylinux1_x86_64.whl
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/pyzmq-19.0.1-cp37-cp37m-manylinux1_x86_64.whl
Collecting ipython>=5.0.0 (from ipykernel>=4.1->qtconsole)
  Using cached https://files.pythonhosted.org/packages/b0/00/afc3968a3cdf5f30c5c9dfb8e6a61e63231d6869a461dc1ff418280c5ea4/ipython-7.14.0-py3-none-any.whl
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/ipython-7.14.0-py3-none-any.whl
Collecting tornado>=4.2 (from ipykernel>=4.1->qtconsole)
  Using cached https://files.pythonhosted.org/packages/95/84/119a46d494f008969bf0c775cb2c6b3579d3c4cc1bb1b41a022aa93ee242/tornado-6.0.4.tar.gz
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/tornado-6.0.4.tar.gz
Collecting decorator (from traitlets->qtconsole)
  Using cached https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/decorator-4.4.2-py2.py3-none-any.whl
Collecting six (from traitlets->qtconsole)
  Using cached https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/six-1.14.0-py2.py3-none-any.whl
Collecting python-dateutil>=2.1 (from jupyter-client>=4.1->qtconsole)
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting backcall (from ipython>=5.0.0->ipykernel>=4.1->qtconsole)
  Using cached https://files.pythonhosted.org/packages/84/71/c8ca4f5bb1e08401b916c68003acf0a0655df935d74d93bf3f3364b310e0/backcall-0.1.0.tar.gz
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/backcall-0.1.0.tar.gz
Collecting pickleshare (from ipython>=5.0.0->ipykernel>=4.1->qtconsole)
  Using cached https://files.pythonhosted.org/packages/9a/41/220f49aaea88bc6fa6cba8d05ecf24676326156c23b991e80b3f2fc24c77/pickleshare-0.7.5-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/pickleshare-0.7.5-py2.py3-none-any.whl
Collecting setuptools>=18.5 (from ipython>=5.0.0->ipykernel>=4.1->qtconsole)
  Using cached https://files.pythonhosted.org/packages/09/27/98ef5f13ca9c63d9d8601e739817839dde55baeb105a6c32fc8f24daddc2/setuptools-46.3.0-py3-none-any.whl
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/setuptools-46.3.0-py3-none-any.whl
Collecting pexpect; sys_platform != "win32" (from ipython>=5.0.0->ipykernel>=4.1->qtconsole)
  Using cached https://files.pythonhosted.org/packages/39/7b/88dbb785881c28a102619d46423cb853b46dbccc70d3ac362d99773a78ce/pexpect-4.8.0-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/pexpect-4.8.0-py2.py3-none-any.whl
Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 (from ipython>=5.0.0->ipykernel>=4.1->qtconsole)
  Using cached https://files.pythonhosted.org/packages/e4/a7/81b39aa50e9284fe2cb21cc7fb7de7817b224172d42793fd57451d38842b/prompt_toolkit-3.0.5-py3-none-any.whl
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/prompt_toolkit-3.0.5-py3-none-any.whl
Collecting jedi>=0.10 (from ipython>=5.0.0->ipykernel>=4.1->qtconsole)
  Using cached https://files.pythonhosted.org/packages/f3/3f/67f027e18c60a800875df1a0894a2436ce9053637fa39725766e937c0a71/jedi-0.17.0-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/jedi-0.17.0-py2.py3-none-any.whl
Collecting ptyprocess>=0.5 (from pexpect; sys_platform != "win32"->ipython>=5.0.0->ipykernel>=4.1->qtconsole)
  Using cached https://files.pythonhosted.org/packages/d1/29/605c2cc68a9992d18dada28206eeada56ea4bd07a239669da41674648b6f/ptyprocess-0.6.0-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/ptyprocess-0.6.0-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.0.0->ipykernel>=4.1->qtconsole)
  Using cached https://files.pythonhosted.org/packages/f6/d5/1ecdac957e3ea12c1b319fcdee8b6917ffaff8b4644d673c4d72d2f20b49/wcwidth-0.1.9-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/wcwidth-0.1.9-py2.py3-none-any.whl
Collecting parso>=0.7.0 (from jedi>=0.10->ipython>=5.0.0->ipykernel>=4.1->qtconsole)
  Using cached https://files.pythonhosted.org/packages/b5/61/998cce9e7476de000d031874df26a18f67cb73448164fc44a98f0c55920b/parso-0.7.0-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/parso-0.7.0-py2.py3-none-any.whl
Successfully downloaded qtconsole pygments jupyter-core qtpy ipython-genutils ipykernel traitlets jupyter-client pyzmq ipython tornado decorator six python-dateutil backcall pickleshare setuptools pexpect prompt-toolkit jedi ptyprocess wcwidth parso
You are using pip version 19.0.3, however version 20.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Looking in indexes: https://pypi.org/simple, https://nexus.irap.omp.eu/repository/pypi/simple
Collecting qtconsole
  Using cached https://files.pythonhosted.org/packages/80/c5/58838a675de252a810a6c13eb47d1d58c1e5952c5f0c8a228b309182f97e/qtconsole-4.7.4.tar.gz
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/qtconsole-4.7.4.tar.gz
Collecting traitlets (from qtconsole)
  Using cached https://files.pythonhosted.org/packages/75/b0/43deb021bc943f18f07cbe3dac1d681626a48997b7ffa1e7fb14ef922b21/traitlets-4.3.3.tar.gz
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/traitlets-4.3.3.tar.gz
Collecting ipython_genutils (from qtconsole)
  Using cached https://files.pythonhosted.org/packages/e8/69/fbeffffc05236398ebfcfb512b6d2511c622871dca1746361006da310399/ipython_genutils-0.2.0.tar.gz
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/ipython_genutils-0.2.0.tar.gz
Collecting jupyter_core (from qtconsole)
  Using cached https://files.pythonhosted.org/packages/28/64/8bdde111be57a2a3d54376db29b5f25ab9c68ffd3d6554989db24d5c1b7a/jupyter_core-4.6.3.tar.gz
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/jupyter_core-4.6.3.tar.gz
Collecting jupyter_client>=4.1 (from qtconsole)
  Using cached https://files.pythonhosted.org/packages/fa/84/440ef480bb829ac648f8e9d7f17c9e2b2470de18ccab989ffa25a64c8c9f/jupyter_client-6.1.3.tar.gz
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/jupyter_client-6.1.3.tar.gz
Collecting pygments (from qtconsole)
  Using cached https://files.pythonhosted.org/packages/6e/4d/4d2fe93a35dfba417311a4ff627489a947b01dc0cc377a3673c00cf7e4b2/Pygments-2.6.1.tar.gz
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/Pygments-2.6.1.tar.gz
Collecting ipykernel>=4.1 (from qtconsole)
  Using cached https://files.pythonhosted.org/packages/c1/43/a7c6398e3ca3748781f7cd13c1b0d17725ee5bd3c1df39a3e8d66341ca3a/ipykernel-5.2.1.tar.gz
  Saved /tmp/pip-generator-python3-qtconsole-rcbrf_3h/ipykernel-5.2.1.tar.gz
  Installing build dependencies ... error
  Complete output from command /home/nath/divers/flatpaks/org.cadquery.cq-editor-oce/CQ-editor/.venv/bin/python /home/nath/divers/flatpaks/org.cadquery.cq-editor-oce/CQ-editor/.venv/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-w81p8ug0/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://nexus.irap.omp.eu/repository/pypi/simple -- setuptools wheel ipython>=5 jupyter_core>=4.2 jupyter_client:
  Looking in indexes: https://pypi.org/simple, https://nexus.irap.omp.eu/repository/pypi/simple, https://nexus.irap.omp.eu/repository/pypi/simple
  Collecting setuptools
    Using cached https://files.pythonhosted.org/packages/68/91/cc0107f3b8aa90968d11ea3334d89d5c63a48b31236f40a80373cc3aec74/setuptools-46.3.0.zip
  Collecting wheel
    Using cached https://files.pythonhosted.org/packages/75/28/521c6dc7fef23a68368efefdcd682f5b3d1d58c2b90b06dc1d0b805b51ae/wheel-0.34.2.tar.gz
  Collecting ipython>=5
    Using cached https://files.pythonhosted.org/packages/cc/c8/500d15efe49f38c36d36ee2433dccc34fc47fc56f40fd38e194d47c142c8/ipython-7.14.0.tar.gz
  Collecting jupyter_core>=4.2
    Using cached https://files.pythonhosted.org/packages/28/64/8bdde111be57a2a3d54376db29b5f25ab9c68ffd3d6554989db24d5c1b7a/jupyter_core-4.6.3.tar.gz
  Collecting jupyter_client
    Using cached https://files.pythonhosted.org/packages/fa/84/440ef480bb829ac648f8e9d7f17c9e2b2470de18ccab989ffa25a64c8c9f/jupyter_client-6.1.3.tar.gz
  Collecting jedi>=0.10 (from ipython>=5)
    Using cached https://files.pythonhosted.org/packages/e3/5b/65ff9c102d92bf719dfaeff57bc8074d68f26ea480005704a956da995799/jedi-0.17.0.tar.gz
  Collecting decorator (from ipython>=5)
    Using cached https://files.pythonhosted.org/packages/da/93/84fa12f2dc341f8cf5f022ee09e109961055749df2d0c75c5f98746cfe6c/decorator-4.4.2.tar.gz
  Collecting pickleshare (from ipython>=5)
    Using cached https://files.pythonhosted.org/packages/d8/b6/df3c1c9b616e9c0edbc4fbab6ddd09df9535849c64ba51fcb6531c32d4d8/pickleshare-0.7.5.tar.gz
  Collecting traitlets>=4.2 (from ipython>=5)
    Using cached https://files.pythonhosted.org/packages/75/b0/43deb021bc943f18f07cbe3dac1d681626a48997b7ffa1e7fb14ef922b21/traitlets-4.3.3.tar.gz
  Collecting prompt_toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 (from ipython>=5)
    Using cached https://files.pythonhosted.org/packages/69/19/3aa4bf17e1cbbdfe934eb3d5b394ae9a0a7fb23594a2ff27e0fdaf8b4c59/prompt_toolkit-3.0.5.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Collecting pygments (from ipython>=5)
    Using cached https://files.pythonhosted.org/packages/6e/4d/4d2fe93a35dfba417311a4ff627489a947b01dc0cc377a3673c00cf7e4b2/Pygments-2.6.1.tar.gz
  Collecting backcall (from ipython>=5)
    Using cached https://files.pythonhosted.org/packages/84/71/c8ca4f5bb1e08401b916c68003acf0a0655df935d74d93bf3f3364b310e0/backcall-0.1.0.tar.gz
  Collecting pexpect (from ipython>=5)
    Using cached https://files.pythonhosted.org/packages/e5/9b/ff402e0e930e70467a7178abb7c128709a30dfb22d8777c043e501bc1b10/pexpect-4.8.0.tar.gz
  Collecting pyzmq>=13 (from jupyter_client)
    Using cached https://files.pythonhosted.org/packages/86/08/e5fc492317cc9d65b32d161c6014d733e8ab20b5e78e73eca63f53b17004/pyzmq-19.0.1.tar.gz
  Collecting python-dateutil>=2.1 (from jupyter_client)
    Using cached https://files.pythonhosted.org/packages/be/ed/5bbc91f03fa4c839c4c7360375da77f9659af5f7086b7a7bdda65771c8e0/python-dateutil-2.8.1.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Collecting tornado>=4.1 (from jupyter_client)
    Using cached https://files.pythonhosted.org/packages/95/84/119a46d494f008969bf0c775cb2c6b3579d3c4cc1bb1b41a022aa93ee242/tornado-6.0.4.tar.gz
  Collecting parso>=0.7.0 (from jedi>=0.10->ipython>=5)
    Using cached https://files.pythonhosted.org/packages/fe/24/c30eb4be8a24b965cfd6e2e6b41180131789b44042112a16f9eb10c80f6e/parso-0.7.0.tar.gz
  Collecting ipython_genutils (from traitlets>=4.2->ipython>=5)
    Using cached https://files.pythonhosted.org/packages/e8/69/fbeffffc05236398ebfcfb512b6d2511c622871dca1746361006da310399/ipython_genutils-0.2.0.tar.gz
  Collecting six (from traitlets>=4.2->ipython>=5)
    Using cached https://files.pythonhosted.org/packages/21/9f/b251f7f8a76dec1d6651be194dfba8fb8d7781d10ab3987190de8391d08e/six-1.14.0.tar.gz
  Collecting wcwidth (from prompt_toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5)
    Using cached https://files.pythonhosted.org/packages/25/9d/0acbed6e4a4be4fc99148f275488580968f44ddb5e69b8ceb53fc9df55a0/wcwidth-0.1.9.tar.gz
  Collecting ptyprocess>=0.5 (from pexpect->ipython>=5)
    Using cached https://files.pythonhosted.org/packages/7d/2d/e4b8733cf79b7309d84c9081a4ab558c89d8c89da5961bf4ddb050ca1ce0/ptyprocess-0.6.0.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'error'
    Complete output from command /home/nath/divers/flatpaks/org.cadquery.cq-editor-oce/CQ-editor/.venv/bin/python /home/nath/divers/flatpaks/org.cadquery.cq-editor-oce/CQ-editor/.venv/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-k06dl0z6/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://nexus.irap.omp.eu/repository/pypi/simple --extra-index-url https://nexus.irap.omp.eu/repository/pypi/simple -- flit:
    Looking in indexes: https://pypi.org/simple, https://nexus.irap.omp.eu/repository/pypi/simple, https://nexus.irap.omp.eu/repository/pypi/simple, https://nexus.irap.omp.eu/repository/pypi/simple
    Collecting flit
      Using cached https://files.pythonhosted.org/packages/20/96/b7d1e668b90270d0d68a8360ce3d01ed5f34aada55aaeb0c9bf3e9f03ae2/flit-2.3.0.tar.gz
      Installing build dependencies: started
      Installing build dependencies: finished with status 'error'
      Complete output from command /home/nath/divers/flatpaks/org.cadquery.cq-editor-oce/CQ-editor/.venv/bin/python /home/nath/divers/flatpaks/org.cadquery.cq-editor-oce/CQ-editor/.venv/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-nmfgqf1h/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://nexus.irap.omp.eu/repository/pypi/simple --extra-index-url https://nexus.irap.omp.eu/repository/pypi/simple --extra-index-url https://nexus.irap.omp.eu/repository/pypi/simple -- "flit_core >=2.3.0,<4":
      Looking in indexes: https://pypi.org/simple, https://nexus.irap.omp.eu/repository/pypi/simple, https://nexus.irap.omp.eu/repository/pypi/simple, https://nexus.irap.omp.eu/repository/pypi/simple, https://nexus.irap.omp.eu/repository/pypi/simple
      Collecting flit_core<4,>=2.3.0
        Using cached https://files.pythonhosted.org/packages/bb/92/e51c58d463ebbabb7b226662655cef6d17d3b4b83f570b08f6be0fe2b1b8/flit_core-2.3.0.tar.gz
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
      Exception:
      Traceback (most recent call last):
        File "/home/nath/divers/flatpaks/org.cadquery.cq-editor-oce/CQ-editor/.venv/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 179, in main
          status = self.run(options, args)
        File "/home/nath/divers/flatpaks/org.cadquery.cq-editor-oce/CQ-editor/.venv/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 315, in run
          resolver.resolve(requirement_set)
        File "/home/nath/divers/flatpaks/org.cadquery.cq-editor-oce/CQ-editor/.venv/lib/python3.7/site-packages/pip/_internal/resolve.py", line 131, in resolve
          self._resolve_one(requirement_set, req)
        File "/home/nath/divers/flatpaks/org.cadquery.cq-editor-oce/CQ-editor/.venv/lib/python3.7/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
          abstract_dist = self._get_abstract_dist_for(req_to_install)
        File "/home/nath/divers/flatpaks/org.cadquery.cq-editor-oce/CQ-editor/.venv/lib/python3.7/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
          self.require_hashes
        File "/home/nath/divers/flatpaks/org.cadquery.cq-editor-oce/CQ-editor/.venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 349, in prepare_linked_requirement
          abstract_dist.prep_for_dist(finder, self.build_isolation)
        File "/home/nath/divers/flatpaks/org.cadquery.cq-editor-oce/CQ-editor/.venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 149, in prep_for_dist
          reqs = self.req.pep517_backend.get_requires_for_build_wheel()
        File "/home/nath/divers/flatpaks/org.cadquery.cq-editor-oce/CQ-editor/.venv/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 71, in get_requires_for_build_wheel
          'config_settings': config_settings
        File "/home/nath/divers/flatpaks/org.cadquery.cq-editor-oce/CQ-editor/.venv/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 162, in _call_hook
          raise BackendUnavailable
      pip._vendor.pep517.wrappers.BackendUnavailable
      You are using pip version 19.0.3, however version 20.1 is available.
      You should consider upgrading via the 'pip install --upgrade pip' command.
  
      ----------------------------------------
    Command "/home/nath/divers/flatpaks/org.cadquery.cq-editor-oce/CQ-editor/.venv/bin/python /home/nath/divers/flatpaks/org.cadquery.cq-editor-oce/CQ-editor/.venv/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-nmfgqf1h/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://nexus.irap.omp.eu/repository/pypi/simple --extra-index-url https://nexus.irap.omp.eu/repository/pypi/simple --extra-index-url https://nexus.irap.omp.eu/repository/pypi/simple -- "flit_core >=2.3.0,<4"" failed with error code 2 in None
    You are using pip version 19.0.3, however version 20.1 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
  
    ----------------------------------------
  Command "/home/nath/divers/flatpaks/org.cadquery.cq-editor-oce/CQ-editor/.venv/bin/python /home/nath/divers/flatpaks/org.cadquery.cq-editor-oce/CQ-editor/.venv/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-k06dl0z6/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://nexus.irap.omp.eu/repository/pypi/simple --extra-index-url https://nexus.irap.omp.eu/repository/pypi/simple -- flit" failed with error code 1 in None
  You are using pip version 19.0.3, however version 20.1 is available.
  You should consider upgrading via the 'pip install --upgrade pip' command.
  
  ----------------------------------------
Command "/home/nath/divers/flatpaks/org.cadquery.cq-editor-oce/CQ-editor/.venv/bin/python /home/nath/divers/flatpaks/org.cadquery.cq-editor-oce/CQ-editor/.venv/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-w81p8ug0/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://nexus.irap.omp.eu/repository/pypi/simple -- setuptools wheel ipython>=5 jupyter_core>=4.2 jupyter_client" failed with error code 1 in None
You are using pip version 19.0.3, however version 20.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Failed to download qtconsole
Please fix the module manually in the generated file
</pre></details>

**Comment by roipoussiere** [comment]
Fixed. I was inside a virtual environment. :smile:
