### ISSUE TITLE
flatpak-pip-generator: kiwisolver-1.2.0 now throws ERROR: Command errored out with exit status 1

### ISSUE THREAD

**Issue by leinardi** [flatpak/flatpak-builder-tools#131]
While generating the dependencies for `matplotlib==3.2.2`, `kiwisolver` throws this error:

```
Collecting matplotlib==3.2.2
  Using cached matplotlib-3.2.2-cp38-cp38-manylinux1_x86_64.whl (12.4 MB)
  Saved /tmp/pip-generator-python3-matplotlib-wis6876m/matplotlib-3.2.2-cp38-cp38-manylinux1_x86_64.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
  Saved /tmp/pip-generator-python3-matplotlib-wis6876m/pyparsing-2.4.7-py2.py3-none-any.whl
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
  Saved /tmp/pip-generator-python3-matplotlib-wis6876m/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.2.0-cp38-cp38-manylinux1_x86_64.whl (92 kB)
  Saved /tmp/pip-generator-python3-matplotlib-wis6876m/kiwisolver-1.2.0-cp38-cp38-manylinux1_x86_64.whl
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
  Saved /tmp/pip-generator-python3-matplotlib-wis6876m/cycler-0.10.0-py2.py3-none-any.whl
Collecting numpy>=1.11
  Using cached numpy-1.19.0-cp38-cp38-manylinux2010_x86_64.whl (14.6 MB)
  Saved /tmp/pip-generator-python3-matplotlib-wis6876m/numpy-1.19.0-cp38-cp38-manylinux2010_x86_64.whl
Collecting six>=1.5
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
  Saved /tmp/pip-generator-python3-matplotlib-wis6876m/six-1.15.0-py2.py3-none-any.whl
Successfully downloaded matplotlib pyparsing python-dateutil kiwisolver cycler numpy six
WARNING: You are using pip version 20.1; however, version 20.1.1 is available.
You should consider upgrading via the '/home/leinardi/Workspace/gitlab/gkraken/venv/bin/python -m pip install --upgrade pip' command.
Collecting matplotlib==3.2.2
  Using cached matplotlib-3.2.2.tar.gz (40.3 MB)
  Saved /tmp/pip-generator-python3-matplotlib-wis6876m/matplotlib-3.2.2.tar.gz
Collecting cycler>=0.10
  Using cached cycler-0.10.0.tar.gz (16 kB)
  Saved /tmp/pip-generator-python3-matplotlib-wis6876m/cycler-0.10.0.tar.gz
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.2.0.tar.gz (52 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/leinardi/Workspace/gitlab/gkraken/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-download-v8fjl1aq/kiwisolver/setup.py'"'"'; __file__='"'"'/tmp/pip-download-v8fjl1aq/kiwisolver/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1j7v2s4g
         cwd: /tmp/pip-download-v8fjl1aq/kiwisolver/
    Complete output (44 lines):
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: /home/leinardi/Workspace/gitlab/gkraken/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-nw_ibdgu/cppy/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-nw_ibdgu/cppy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-3r0g1iq2
           cwd: /tmp/pip-wheel-nw_ibdgu/cppy/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
    
      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for cppy
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/home/leinardi/Workspace/gitlab/gkraken/venv/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/home/leinardi/Workspace/gitlab/gkraken/venv/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpc0d7ietx', '--quiet', 'cppy>=1.1.0']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-download-v8fjl1aq/kiwisolver/setup.py", line 59, in <module>
        setup(
      File "/home/leinardi/Workspace/gitlab/gkraken/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 143, in setup
        _install_setup_requires(attrs)
      File "/home/leinardi/Workspace/gitlab/gkraken/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 138, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/leinardi/Workspace/gitlab/gkraken/venv/lib/python3.8/site-packages/setuptools/dist.py", line 695, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/home/leinardi/Workspace/gitlab/gkraken/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 781, in resolve
        dist = best[req.key] = env.best_match(
      File "/home/leinardi/Workspace/gitlab/gkraken/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1066, in best_match
        return self.obtain(req, installer)
      File "/home/leinardi/Workspace/gitlab/gkraken/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1078, in obtain
        return installer(requirement)
      File "/home/leinardi/Workspace/gitlab/gkraken/venv/lib/python3.8/site-packages/setuptools/dist.py", line 754, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/home/leinardi/Workspace/gitlab/gkraken/venv/lib/python3.8/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/home/leinardi/Workspace/gitlab/gkraken/venv/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpc0d7ietx', '--quiet', 'cppy>=1.1.0']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

In the past worked fine and the last working version was I used was `kiwisolver-1.1.0`.

**Comment by tedb** [comment]
Does this answer help? https://github.com/flatpak/flatpak-builder-tools/issues/90#issuecomment-650902678

**Comment by TingPing** [comment]
@A6GibKm

**Comment by TingPing** [comment]
In theory this is fixed by the merged PR, reopen if not true.
