### ISSUE TITLE
flatpak-pip-generator cannot handle Git dependencies

### ISSUE THREAD

**Issue by strugee** [flatpak/flatpak-builder-tools#133]
STR:

1. Create `requirements.txt` with one line in it: `git+git://github.com/Amulet-Team/Amulet-Core.git@4986e49c143abded07e548b486d71c5085a77d41`
2. Run `flatpak-pip-generator --requirements-file=requirements.txt`

This causes the following error:

```
Traceback (most recent call last):
  File "../Amulet-Map-Editor/flatpak-builder-tools/pip/flatpak-pip-generator", line 112, in <module>
    with tempfile.TemporaryDirectory(prefix=tempdir_prefix) as tempdir:
  File "/usr/lib/python3.8/tempfile.py", line 920, in __init__
    self.name = mkdtemp(suffix, prefix, dir)
  File "/usr/lib/python3.8/tempfile.py", line 498, in mkdtemp
    _os.mkdir(file, 0o700)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-generator-python3-git+git://github.com/Amulet-Team/Amulet-Core.git@4986e49c143abded07e548b486d71c5085a77d41-dif6ah2s'
```

I'm running commit 8dd64fc6ab152623b015e793ff726a6592f17248 of this repository.

**Comment by strugee** [comment]
Fixed in 9a12506a9d384770dd40b333967b53afc0762ae2, or somewhere around there.
