### ISSUE TITLE
node: AssertionError on package version although it is available

### ISSUE THREAD

**Issue by ghisvail** [flatpak/flatpak-builder-tools#145]
I tried generating the sources from the following [lock file](https://github.com/zulip/zulip-desktop/blob/4b3608fc1ee58793560135ba53a00301592d4877/package-lock.json).

I am getting the following assertion errors:

```
Found 1 lockfiles.
Reading packages from lockfiles...
1475 packages read.
Generating packages [1473/1475] ms @ 2.0.0Task exception was never retrieved                             
future: <Task finished coro=<GeneratorProgress._generate() done, defined at ./node/flatpak-node-generator.py:1431> exception=AssertionError('entities versions available are 0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.4.0, 0.4.1, 0.5.0, 1.0.0, 1.1.0, 1.1.1, 1.1.2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, not https://registry.npmjs.org/entities/-/entities-1.1.2.tgz')>
Traceback (most recent call last):
  File "./node/flatpak-node-generator.py", line 1433, in _generate
    await self.module_provider.generate_package(package)
  File "./node/flatpak-node-generator.py", line 1110, in generate_package
    source = await self.resolve_source(package)
  File "./node/flatpak-node-generator.py", line 1086, in resolve_source
    f'{package.name} versions available are {", ".join(versions)}, not {package.version}'
AssertionError: entities versions available are 0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.4.0, 0.4.1, 0.5.0, 1.0.0, 1.1.0, 1.1.1, 1.1.2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, not https://registry.npmjs.org/entities/-/entities-1.1.2.tgz
Task exception was never retrieved
future: <Task finished coro=<GeneratorProgress._generate() done, defined at ./node/flatpak-node-generator.py:1431> exception=AssertionError('readable-stream versions available are 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.1.0, 0.2.0, 0.3.0, 0.3.1, 1.0.0, 1.0.1, 1.0.2, 1.0.15, 1.0.17, 1.1.7, 1.1.8, 1.1.9, 1.0.24, 1.0.25, 1.1.10, 1.0.25-1, 1.1.11, 1.0.26, 1.0.26-1, 1.1.11-1, 1.0.26-2, 1.1.12, 1.0.26-3, 1.0.26-4, 1.1.12-1, 1.0.27-1, 1.1.13-1, 1.0.31, 1.1.13, 1.0.32, 1.0.32-1, 1.0.33-1, 1.0.33-2, 1.0.33, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 1.0.34, 1.1.14, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.2.10, 2.2.11, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 3.0.0-rc.1, 3.0.0-rc.2, 3.0.0-rc.3, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.1.0, 3.1.1, 3.2.0, 3.3.0, 3.4.0, 2.3.7, 3.5.0, 3.6.0, not https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.0.tgz')>
Traceback (most recent call last):
  File "./node/flatpak-node-generator.py", line 1433, in _generate
    await self.module_provider.generate_package(package)
  File "./node/flatpak-node-generator.py", line 1110, in generate_package
    source = await self.resolve_source(package)
  File "./node/flatpak-node-generator.py", line 1086, in resolve_source
    f'{package.name} versions available are {", ".join(versions)}, not {package.version}'
AssertionError: readable-stream versions available are 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.1.0, 0.2.0, 0.3.0, 0.3.1, 1.0.0, 1.0.1, 1.0.2, 1.0.15, 1.0.17, 1.1.7, 1.1.8, 1.1.9, 1.0.24, 1.0.25, 1.1.10, 1.0.25-1, 1.1.11, 1.0.26, 1.0.26-1, 1.1.11-1, 1.0.26-2, 1.1.12, 1.0.26-3, 1.0.26-4, 1.1.12-1, 1.0.27-1, 1.1.13-1, 1.0.31, 1.1.13, 1.0.32, 1.0.32-1, 1.0.33-1, 1.0.33-2, 1.0.33, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 1.0.34, 1.1.14, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.2.10, 2.2.11, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 3.0.0-rc.1, 3.0.0-rc.2, 3.0.0-rc.3, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.1.0, 3.1.1, 3.2.0, 3.3.0, 3.4.0, 2.3.7, 3.5.0, 3.6.0, not https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.0.tgz
```

All packages seem to have their expected version available for download. The error message suggest some parsing error in the version, as I don't expect to see the full URL in the `package.version` field.

**Comment by gasinvein** [comment]
This is not a parse error, the lockfile really has this url in a dependency version field [here](https://github.com/zulip/zulip-desktop/blob/4b3608fc1ee58793560135ba53a00301592d4877/package-lock.json#L9238).

**Comment by refi64** [comment]
I love the way package-lock.json feels like a magic hat, constantly putting out whatever syntax it feels like. Will fix within the next few days.

**Comment by guihkx** [comment]
Sorry to necrobump this, but I'm trying to build an app which lockfile has the same weird versioning scheme:

```json
"vue-loader-v16": {
  "version": "npm:vue-loader@16.1.2",
  "resolved": "https://registry.npmjs.org/vue-loader/-/vue-loader-16.1.2.tgz",
  "integrity": "sha512-8QTxh+Fd+HB6fiL52iEVLKqE9N1JSlMXLR92Ijm6g8PZrwIxckgpqjPDWRP5TWxdiPaHR+alUWsnu1ShQOwt+Q==",
  "dev": true,
  "optional": true,
  "requires": {
    "chalk": "^4.1.0",
    "hash-sum": "^2.0.0",
    "loader-utils": "^2.0.0"
  }
}
```

Here's the complete output when I run `./flatpak-node-generator.py npm -r ~/git/project/package-lock.json`:

```
Found 3 lockfiles.
Reading packages from lockfiles...
1793 packages read.
Generating packages [0/1793] /home/gui/git/flatpak-builder-tools/node/./flatpak-node-generator.py:1483: DeprecationWarning: The explicit passing of coroutine objects to asyncio.wait() is deprecated since Python 3.8, and scheduled for removal in Python 3.11.
  await asyncio.wait(map(self._generate, self.packages))
Generating packages [1792/1793] xtend @ 4.0.2Task exception was never retrieved                                                                                                               
future: <Task finished name='Task-1238' coro=<GeneratorProgress._generate() done, defined at /home/gui/git/flatpak-builder-tools/node/./flatpak-node-generator.py:1475> exception=AssertionError('vue-loader-v16 versions available are 16.0.0-beta.5, 16.0.0-beta.5.1, 16.0.0-beta.5.2, 16.0.0-beta.5.3, 16.0.0-beta.5.4, not npm:vue-loader@16.1.2')>
Traceback (most recent call last):
  File "/home/git/flatpak-builder-tools/node/./flatpak-node-generator.py", line 1477, in _generate
    await self.module_provider.generate_package(package)
  File "/home/gui/git/flatpak-builder-tools/node/./flatpak-node-generator.py", line 1141, in generate_package
    source = await self.resolve_source(package)
  File "/home/gui/git/flatpak-builder-tools/node/./flatpak-node-generator.py", line 1116, in resolve_source
    assert package.version in versions, \
AssertionError: vue-loader-v16 versions available are 16.0.0-beta.5, 16.0.0-beta.5.1, 16.0.0-beta.5.2, 16.0.0-beta.5.3, 16.0.0-beta.5.4, not npm:vue-loader@16.1.2

Wrote 2290 source(s).
```

**Comment by gasinvein** [comment]
@guihkx Well, it's not the same weird versioning scheme, it's a new one. Looks like now there can be some version prefix like `npm:`

**Comment by olof-nord** [comment]
Digging into this further, the vue-loader-v15 package is indeed quite a special one.

> This package contained malicious code and was removed from the registry by the npm security team. A placeholder was published to ensure users are not affected in the future.
Please refer to [www.npmjs.com/advisories?search=vue-loader-v15](http://www.npmjs.com/advisories?search=vue-loader-v15) for more information.

https://www.npmjs.com/package/vue-loader-v15

**Comment by gasinvein** [comment]
@refi64 Do you have any ideas how to properly address this? It seems like handling URLs in `version` field is mandatory for handling foreign-registry (i.e. non-`registry.npmjs.org`) packages (#301).

@olof-nord I've hid your comments because they describe a different case. Feel free to open another issue.

**Comment by refi64** [comment]
oh wow I forgot this issue was a thing :sweat_smile: I'll take a look soon, have an idea but really I need to do some digging into the npm cache first
