### ISSUE TITLE
flatpak-pip-generator fails on cyhunspell==2.0.2

### ISSUE THREAD

**Issue by Jenyay** [flatpak/flatpak-builder-tools#202]
I run command 
``` 
python-pip-generator fails on
```
and I get an error
```
========================================================================
Downloading sources
========================================================================
Running: "pip3 download --exists-action=i --dest /tmp/pip-generator-python3-cyhunspellwqg93fyr -r /tmp/requirements.qgu20cuk"
/home/jenyay/.local/lib/python3.9/site-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/home/jenyay/.local/lib/python3.9/site-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Collecting cyhunspell
  Using cached cyhunspell-2.0.2-cp39-cp39-manylinux2010_x86_64.whl (3.8 MB)
Collecting cacheman>=2.0.6
  Using cached CacheMan-2.1.0-py2.py3-none-any.whl (12 kB)
Collecting future>=0.16.0
  Using cached future-0.18.2.tar.gz (829 kB)
Collecting six>=1.10.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting psutil>=2.1.0
  Using cached psutil-5.8.0-cp39-cp39-manylinux2010_x86_64.whl (293 kB)
Saved /tmp/pip-generator-python3-cyhunspellwqg93fyr/cyhunspell-2.0.2-cp39-cp39-manylinux2010_x86_64.whl
Saved /tmp/pip-generator-python3-cyhunspellwqg93fyr/CacheMan-2.1.0-py2.py3-none-any.whl
Saved /tmp/pip-generator-python3-cyhunspellwqg93fyr/future-0.18.2.tar.gz
Saved /tmp/pip-generator-python3-cyhunspellwqg93fyr/psutil-5.8.0-cp39-cp39-manylinux2010_x86_64.whl
Saved /tmp/pip-generator-python3-cyhunspellwqg93fyr/six-1.15.0-py2.py3-none-any.whl
Successfully downloaded cyhunspell cacheman future psutil six
WARNING: You are using pip version 21.0.1; however, version 21.1.1 is available.
You should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command.
========================================================================
Downloading arch independent packages
========================================================================
Deleting six-1.15.0-py2.py3-none-any.whl
Downloading https://files.pythonhosted.org/packages/6b/34/415834bfdafca3c5f451532e8a8d9ba89a21c9743a0c59fbd0205c7f9426/six-1.15.0.tar.gz
Deleting psutil-5.8.0-cp39-cp39-manylinux2010_x86_64.whl
Downloading https://files.pythonhosted.org/packages/e1/b0/7276de53321c12981717490516b7e612364f2cb372ee8901bd4a66a000d7/psutil-5.8.0.tar.gz
Deleting CacheMan-2.1.0-py2.py3-none-any.whl
Downloading https://files.pythonhosted.org/packages/62/fa/cd8c75d9e72f56964f15b8d86f30dcdb26ec3e6506871bbd7e5da0174343/CacheMan-2.1.0.tar.gz
Traceback (most recent call last):
  File "/home/jenyay/Загрузки/3/flatpak-pip-generator.py", line 231, in <module>
    url = get_tar_package_url_pypi(name, version)
  File "/home/jenyay/Загрузки/3/flatpak-pip-generator.py", line 68, in get_tar_package_url_pypi
    raise Exception(err)
Exception: Failed to get cyhunspell-2.0.2 source from https://pypi.org/pypi/cyhunspell/2.0.2/json
```

**Comment by hfiguiere** [comment]
Well there is no source for that package.

I filed this upstream:
https://github.com/MSeal/cython_hunspell/issues/31

**Comment by bbhtt** [comment]
The general issue here was sort of "fixed" by https://github.com/flatpak/flatpak-builder-tools/pull/435 in that it will generate a prompt to manually include it, but I'll keep this open as I think we can improve the behaviour.

**Comment by bbhtt** [comment]
A fix for this is somewhat tied to https://github.com/flatpak/flatpak-builder-tools/issues/296, instead of having any fallback I think it'd be better to implement the idea from the other issue.

b) implement `--use-wheel=pkg1,pkg2`
a) If no sdist/none-any wheel, fallback to `--use-wheel=pkg1,pkg2`
