### ISSUE TITLE
[cargo] Issue with Git versions of GTK-rs

### ISSUE THREAD

**Issue by EmmyGH** [flatpak/flatpak-builder-tools#212]
Cargo.toml dependencies:
```toml
[dependencies]
actix-rt = "1.1.1"
bincode = "1.3.2"
cairo-rs = { git = "https://github.com/gtk-rs/gtk-rs-core.git", features = ["png"] }
chrono = { version = "0.4.19", features = ["unstable-locales"] }
cid = "0.6.1"
directories-next = "2.0.0"
futures = "0.3.13"
gdk = { git = "https://github.com/gtk-rs/gtk3-rs.git" }
gdk-pixbuf = { git = "https://github.com/gtk-rs/gtk-rs-core.git" }
gio = { git = "https://github.com/gtk-rs/gtk-rs-core.git" }
glib = { git = "https://github.com/gtk-rs/gtk-rs-core.git" }
gtk = { git = "https://github.com/gtk-rs/gtk3-rs.git", features = ["v3_24_9"], default-features = false }
ipfs = { git = "https://github.com/Christian7573/rust-ipfs.git", branch = "7573" }
ipfs-api = { version = "0.11.0", features = ["actix"], default-features = false }
lazy_static = "1.4.0"
notify-rust = { version = "4.3.0", features = ["images", "z"], default-features = false }
pango = { git = "https://github.com/gtk-rs/gtk-rs-core.git" }
url = "2.2.1"
urlencoding = "1.1.1"
reqwest = { version = "0.11.1", features = ["blocking"] }
tokio = { version = "0.2", features = ["full"] }
webkit2gtk = { git = "https://github.com/EmmyGH/webkit2gtk-rs.git", features = ["v2_30"] }
```

Error:
```python3
Traceback (most recent call last):
  File "/home/emil/Documents/Projects/oku/./flatpak-cargo-generator.py", line 274, in <module>
    main()
  File "/home/emil/Documents/Projects/oku/./flatpak-cargo-generator.py", line 268, in main
    generated_sources = asyncio.run(generate_sources(load_toml(args.cargo_lock),
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/emil/Documents/Projects/oku/./flatpak-cargo-generator.py", line 224, in generate_sources
    for pkg in await asyncio.gather(*pkg_coros):
  File "/home/emil/Documents/Projects/oku/./flatpak-cargo-generator.py", line 191, in get_package_sources
    return await get_git_sources(package, tarball=git_tarballs)
  File "/home/emil/Documents/Projects/oku/./flatpak-cargo-generator.py", line 156, in get_git_sources
    pkg_subpath = git_cargo_packages[name]
KeyError: 'javascriptcore-rs-sys'
```

[`javascriptcore-rs`](https://github.com/gtk-rs/javascriptcore-rs) is a dependency of `webkit2gtk-rs`.

**Comment by gasinvein** [comment]
What's the project are you trying to build and how do you run `flatpak-cargo-generator.py`?

**Comment by gasinvein** [comment]
Ok, this looks somehow similar to #181. Can you please try the generator script with this patch?
```patch
diff --git a/cargo/flatpak-cargo-generator.py b/cargo/flatpak-cargo-generator.py
index 6f9cf78..bfcc15d 100755
--- a/cargo/flatpak-cargo-generator.py
+++ b/cargo/flatpak-cargo-generator.py
@@ -106,6 +106,13 @@ async def get_git_cargo_packages(git_url, commit):
                 with open(subpkg_toml, 'r') as s:
                     pkg_toml = toml.loads(s.read())
                 packages[pkg_toml['package']['name']] = subpkg
+    if 'dependencies' in root_toml:
+        for _, dep in root_toml['dependencies'].items():
+            if 'path' not in dep:
+                continue
+            dep_dir = os.path.normpath(dep['path'])
+            dep_toml = load_toml(os.path.join(git_repo_dir, dep_dir, 'Cargo.toml'))
+            packages[dep_toml['package']['name']] = dep_dir
     logging.debug(f'Packages in repo: {packages}')
     return packages
 
```
If it works for you, I guess I'll need to figure out a common solution for both cases.

**Comment by EmmyGH** [comment]
@gasinvein Your PR, #213, appears to have fixed it! Thanks so much! Hope it gets merged soon.
