### ISSUE TITLE
Handle network resolution failures better

### ISSUE THREAD

**Issue by advaithm** [flatpak/flatpak-builder-tools#221]
Currently due to spotty networking situations I'm struggling to use the npm generator. If for some reason  a download fails instead of handling it gracefully the program locks up and is stuck for minutes at a time before it spits out a trace back. A simple solution would be to "re-try" downloads and attempt downloading package again. 
The error out put in case its required 
```
   addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/lib/python3.9/site-packages/aiohttp/resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
OSError: [Errno 16] Device or resource busy

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nullrequest/moderndeck-flatpak/flatpak-builder-tools/node/flatpak-node-generator.py", line 1555, in _generate
    await self.module_provider.generate_package(package)
  File "/home/nullrequest/moderndeck-flatpak/flatpak-builder-tools/node/flatpak-node-generator.py", line 1209, in generate_package
    source = await self.resolve_source(package)
  File "/home/nullrequest/moderndeck-flatpak/flatpak-builder-tools/node/flatpak-node-generator.py", line 1167, in resolve_source
    raw_data = await Requests.instance.read_all(data_url, cachable=False)
  File "/home/nullrequest/moderndeck-flatpak/flatpak-builder-tools/node/flatpak-node-generator.py", line 279, in read_all
    data = await self._read_all(url)
  File "/home/nullrequest/moderndeck-flatpak/flatpak-builder-tools/node/flatpak-node-generator.py", line 352, in _read_all
    async with self._open_stream(url) as stream:
  File "/usr/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "/home/nullrequest/moderndeck-flatpak/flatpak-builder-tools/node/flatpak-node-generator.py", line 337, in _open_stream
    async with session.get(url) as response:
  File "/usr/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 1011, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host registry.npmjs.org:443 ssl:default [Device or resource busy]
Task exception was never retrieved
future: <Task finished name='Task-578' coro=<GeneratorProgress._generate() done, defined at /home/nullrequest/moderndeck-flatpak/flatpak-builder-tools/node/flatpak-node-generator.py:1553> exception=ClientConnectorError(ConnectionKey(host='registry.npmjs.org', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(16, 'Device or resource busy'))>
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 999, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 865, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/lib/python3.9/site-packages/aiohttp/resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
OSError: [Errno 16] Device or resource busy

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nullrequest/moderndeck-flatpak/flatpak-builder-tools/node/flatpak-node-generator.py", line 1555, in _generate
    await self.module_provider.generate_package(package)
  File "/home/nullrequest/moderndeck-flatpak/flatpak-builder-tools/node/flatpak-node-generator.py", line 1209, in generate_package
    source = await self.resolve_source(package)
  File "/home/nullrequest/moderndeck-flatpak/flatpak-builder-tools/node/flatpak-node-generator.py", line 1167, in resolve_source
    raw_data = await Requests.instance.read_all(data_url, cachable=False)
  File "/home/nullrequest/moderndeck-flatpak/flatpak-builder-tools/node/flatpak-node-generator.py", line 279, in read_all
    data = await self._read_all(url)
  File "/home/nullrequest/moderndeck-flatpak/flatpak-builder-tools/node/flatpak-node-generator.py", line 352, in _read_all
    async with self._open_stream(url) as stream:
  File "/usr/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "/home/nullrequest/moderndeck-flatpak/flatpak-builder-tools/node/flatpak-node-generator.py", line 337, in _open_stream
    async with session.get(url) as response:
  File "/usr/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 1011, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host registry.npmjs.org:443 ssl:default [Device or resource busy]
Task exception was never retrieved
future: <Task finished name='Task-616' coro=<GeneratorProgress._generate() done, defined at /home/nullrequest/moderndeck-flatpak/flatpak-builder-tools/node/flatpak-node-generator.py:1553> exception=ClientConnectorError(ConnectionKey(host='registry.npmjs.org', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(16, 'Device or resource busy'))>
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 999, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 865, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/lib/python3.9/site-packages/aiohttp/resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
OSError: [Errno 16] Device or resource busy
```

**Comment by refi64** [comment]
We *do* have retry support, you can use `--retries`. That being said, this shouldn't be hanging in the first place; I'm aware of that happening sometimes, I just haven't gotten around to figuring out why.

**Comment by advaithm** [comment]
> We *do* have retry support, you can use `--retries`. That being said, this shouldn't be hanging in the first place; I'm aware of that happening sometimes, I just haven't gotten around to figuring out why.

Is there anything I can do to help?
