### ISSUE TITLE
node: AssertionError URL returned an invalid package index

### ISSUE THREAD

**Issue by ghisvail** [flatpak/flatpak-builder-tools#251]
I tried to generate sources for [Bitwarden](https://github.com/bitwarden/desktop) and ran into the following error:

```commandline
$ ./node/flatpak-node-generator.py --xdg-layout -o generated-sources.json npm /path/to/bitwarden/desktop/package-lock.json 
Reading packages from lockfiles...
1236 packages read.
Generating packages [1233/1236] @webassemblyjs/ieee754 @ 1.9.0Task exception was never retrieved                                                                                                                   
future: <Task finished name='Task-563' coro=<GeneratorProgress._generate() done, defined at /home/ghislain/Workspace/flatpak-builder-tools/./node/flatpak-node-generator.py:1651> exception=AssertionError('https://registry.npmjs.org/@bitwarden%2fjslib-common returned an invalid package index')>
Traceback (most recent call last):
  File "/home/ghislain/Workspace/flatpak-builder-tools/./node/flatpak-node-generator.py", line 1653, in _generate
    await self.module_provider.generate_package(package)
  File "/home/ghislain/Workspace/flatpak-builder-tools/./node/flatpak-node-generator.py", line 1299, in generate_package
    source = await self.resolve_source(package)
  File "/home/ghislain/Workspace/flatpak-builder-tools/./node/flatpak-node-generator.py", line 1260, in resolve_source
    assert 'versions' in data, f'{data_url} returned an invalid package index'
AssertionError: https://registry.npmjs.org/@bitwarden%2fjslib-common returned an invalid package index
Task exception was never retrieved
future: <Task finished name='Task-306' coro=<GeneratorProgress._generate() done, defined at /home/ghislain/Workspace/flatpak-builder-tools/./node/flatpak-node-generator.py:1651> exception=AssertionError('https://registry.npmjs.org/@bitwarden%2fjslib-electron returned an invalid package index')>
Traceback (most recent call last):
  File "/home/ghislain/Workspace/flatpak-builder-tools/./node/flatpak-node-generator.py", line 1653, in _generate
    await self.module_provider.generate_package(package)
  File "/home/ghislain/Workspace/flatpak-builder-tools/./node/flatpak-node-generator.py", line 1299, in generate_package
    source = await self.resolve_source(package)
  File "/home/ghislain/Workspace/flatpak-builder-tools/./node/flatpak-node-generator.py", line 1260, in resolve_source
    assert 'versions' in data, f'{data_url} returned an invalid package index'
AssertionError: https://registry.npmjs.org/@bitwarden%2fjslib-electron returned an invalid package index
Task exception was never retrieved
future: <Task finished name='Task-872' coro=<GeneratorProgress._generate() done, defined at /home/ghislain/Workspace/flatpak-builder-tools/./node/flatpak-node-generator.py:1651> exception=AssertionError('https://registry.npmjs.org/@bitwarden%2fjslib-angular returned an invalid package index')>
Traceback (most recent call last):
  File "/home/ghislain/Workspace/flatpak-builder-tools/./node/flatpak-node-generator.py", line 1653, in _generate
    await self.module_provider.generate_package(package)
  File "/home/ghislain/Workspace/flatpak-builder-tools/./node/flatpak-node-generator.py", line 1299, in generate_package
    source = await self.resolve_source(package)
  File "/home/ghislain/Workspace/flatpak-builder-tools/./node/flatpak-node-generator.py", line 1260, in resolve_source
    assert 'versions' in data, f'{data_url} returned an invalid package index'
AssertionError: https://registry.npmjs.org/@bitwarden%2fjslib-angular returned an invalid package index

Traceback (most recent call last):
  File "/home/ghislain/Workspace/flatpak-builder-tools/./node/flatpak-node-generator.py", line 1852, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/ghislain/Workspace/flatpak-builder-tools/./node/flatpak-node-generator.py", line 1813, in main
    await progress.run()
  File "/home/ghislain/Workspace/flatpak-builder-tools/./node/flatpak-node-generator.py", line 1210, in __exit__
    self._finalize()
  File "/home/ghislain/Workspace/flatpak-builder-tools/./node/flatpak-node-generator.py", line 1325, in _finalize
    index = async_index.result()
asyncio.exceptions.InvalidStateError: Result is not set.
```

**Comment by gasinvein** [comment]
Please try flatpak-builder-tools with this patch and tell if it works for you (including complete app build, not just generating sources):
```patch
diff --git a/node/flatpak-node-generator.py b/node/flatpak-node-generator.py
index 63bafb1..74d6c84 100755
--- a/node/flatpak-node-generator.py
+++ b/node/flatpak-node-generator.py
@@ -1291,6 +1291,10 @@ class NpmModuleProvider(ModuleProvider):
 
     async def generate_package(self, package: Package) -> None:
         self.all_lockfiles.add(package.lockfile)
+
+        if package.version.startswith('file:'):
+            return
+
         source = package.source
 
         assert not isinstance(source, ResolvedSource)
```

**Comment by ghisvail** [comment]
Ok, now it completes with the proposed patch. Build to be tested next.

**Comment by threema-danilo** [comment]
@gasinvein this worked for me. (I'm using some file-URLs to git submodules in my project.)

**Comment by ghisvail** [comment]
@gasinvein go for it. Thanks for taking care of it.

**Comment by olof-nord** [comment]
> Please try flatpak-builder-tools with this patch and tell if it works for you (including complete app build, not just generating sources):
> 
> ```diff
> diff --git a/node/flatpak-node-generator.py b/node/flatpak-node-generator.py
> index 63bafb1..74d6c84 100755
> --- a/node/flatpak-node-generator.py
> +++ b/node/flatpak-node-generator.py
> @@ -1291,6 +1291,10 @@ class NpmModuleProvider(ModuleProvider):
>  
>      async def generate_package(self, package: Package) -> None:
>          self.all_lockfiles.add(package.lockfile)
> +
> +        if package.version.startswith('file:'):
> +            return
> +
>          source = package.source
>  
>          assert not isinstance(source, ResolvedSource)
> ```

I really appreciate the recent `flatpak-node-generator.py` work done, and if we could merge this one then my usage of it would work flawless. What speaks against it? It does address my problems of generating the sources list.
