### ISSUE TITLE
Unable to download `tensorboard_data_server-0.6.1`

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flatpak/flatpak-builder-tools#328]
### flatpak-builder version

1.2.2

### Linux distribution and version

Fedora 36 toolbx container (on Fedora 37 Silverblue host)

### Affected flatpak-builder tool

pip/flatpak-pip-generator

### Source repository URL

https://github.com/xinntao/Real-ESRGAN

### Description

Running `flatpak-pip-generator` against Real-ESRGAN's [`requirements.txt`](https://github.com/xinntao/Real-ESRGAN/blob/5ca1078535923d485892caee7d7804380bfc87fd/requirements.txt) fails to generate the manifest with the following error:
```
========================================================================
Downloading arch independent packages
========================================================================
Deleting MarkupSafe-2.1.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Downloading https://files.pythonhosted.org/packages/1d/97/2288fe498044284f39ab8950703e88abbac2abbdf65524d576157af70556/MarkupSafe-2.1.1.tar.gz
Deleting kiwisolver-1.4.4-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
Downloading https://files.pythonhosted.org/packages/5f/5c/272a7dd49a1914f35cd8d6d9f386defa8b047f6fbd06badd6b77b3ba24e7/kiwisolver-1.4.4.tar.gz
Deleting contourpy-1.0.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Downloading https://files.pythonhosted.org/packages/38/b3/d6fd43ab2eadce72ac089328d80e9cdf274efdb79a9933aaf52ef1621e99/contourpy-1.0.5.tar.gz
Deleting matplotlib-3.6.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Downloading https://files.pythonhosted.org/packages/0f/23/2eed6f40e1afca9c272fa7c13b437b7784c94a0c180f796c0da114265bf9/matplotlib-3.6.1.tar.gz
Traceback (most recent call last):
  File "/var/home/TheEvilSkeleton/flatpak-builder-tools/pip/flatpak-pip-generator", line 259, in <module>
    url = get_tar_package_url_pypi(name, version)
  File "/var/home/TheEvilSkeleton/flatpak-builder-tools/pip/flatpak-pip-generator", line 79, in get_tar_package_url_pypi
    raise Exception(err)
Exception: Failed to get tensorboard_data_server-0.6.1 source from https://pypi.org/pypi/tensorboard_data_server/0.6.1/json
```

**Comment by hfiguiere** [comment]
https://pypi.org/project/tensorboard-data-server/ show there is no source package. However it has a "any" wheel.

**Comment by TheEvilSkeleton** [comment]
Is there a way I can cherry pick the any wheel?

**Comment by razzeee** [comment]
I'm seeing the same, when it tries to download this for e.g. https://pypi.org/pypi/shiboken6/6.4.1/json

**Comment by hfiguiere** [comment]
This was closed with #435
