### ISSUE TITLE
Support for lockfileVersion 3 in flatpak-node-generator

### ISSUE THREAD

**Issue by zigazajc007** [flatpak/flatpak-builder-tools#333]
### flatpak-builder version

1.2.3

### Linux distribution and version

Fedora 37

### Affected flatpak-builder tool

node/flatpak-node-generator.py

### Description

It seems that lockfileVersion 3 is not supported.

```bash
[ziga@ziga Passky-Desktop]$ flatpak-node-generator npm package-lock.json -o generated-sources.json
Reading packages from lockfiles...
Traceback (most recent call last):
  File "/home/ziga/.local/bin/flatpak-node-generator", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ziga/.local/lib/python3.11/site-packages/flatpak_node_generator/main.py", line 277, in main
    asyncio.run(_async_main())
  File "/usr/lib64/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ziga/.local/lib/python3.11/site-packages/flatpak_node_generator/main.py", line 198, in _async_main
    packages.update(lockfile_provider.process_lockfile(lockfile))
  File "/home/ziga/.local/lib/python3.11/site-packages/flatpak_node_generator/providers/npm.py", line 101, in process_lockfile
    assert data['lockfileVersion'] <= 2, data['lockfileVersion']
AssertionError: 3
```

**Comment by gasinvein** [comment]
The app seems to use Yarn and has `yarn.lock` in the upstream source, why bother with NPM at all?

**Comment by zigazajc007** [comment]
Yeah I have switched to yarn, but for others that might be still using npm, support for v3 shouldn't harm anyone.

**Comment by gasinvein** [comment]
Ah, I see. Do you know which nodejs and/or npm versions produce v3 lockfiles?

**Comment by zigazajc007** [comment]
I'm on Fedora 37.

Using NPM 9.1.2 and nodejs v18.12.1

**Comment by gasinvein** [comment]
It looks like nodejs v18.12.1 dist tarball has NPM 8.19.2, so I suppose Fedora ships NPM separately.

@refi64 What do you think, how can we test a NPM version newer than what the latest SDK extension has?

**Comment by zigazajc007** [comment]
I'm always keeping NPM up to date with `npm install -g npm@latest`, so that's probably why I'm using the latest version.
