### ISSUE TITLE
Node: Generic error KeyError: 'resolved'

### ISSUE THREAD

**Issue by marc0x1** [flatpak/flatpak-builder-tools#358]
### flatpak-builder version

1.3.3

### Linux distribution and version

Fedora 38

### Affected flatpak-builder tool

node/flatpak-node-generator.py

### flatpak-builder tool cli args

yarn -r yarn.lock

### Source repository URL

https://github.com/open-duelyst/duelyst

### Description

flatpak-node-generator yarn -r yarn.lock:
```

Found 2 lockfiles.
Reading packages from lockfiles...
Traceback (most recent call last):
  File "/home/marco/.local/bin/flatpak-node-generator", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/marco/.local/pipx/venvs/flatpak-node-generator/lib64/python3.11/site-packages/flatpak_node_generator/main.py", line 277, in main
    asyncio.run(_async_main())
  File "/usr/lib64/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/marco/.local/pipx/venvs/flatpak-node-generator/lib64/python3.11/site-packages/flatpak_node_generator/main.py", line 198, in _async_main
    packages.update(lockfile_provider.process_lockfile(lockfile))
  File "/home/marco/.local/pipx/venvs/flatpak-node-generator/lib64/python3.11/site-packages/flatpak_node_generator/providers/yarn.py", line 107, in process_lockfile
    yield self.process_package(lockfile, name_line, package)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/.local/pipx/venvs/flatpak-node-generator/lib64/python3.11/site-packages/flatpak_node_generator/providers/yarn.py", line 92, in process_package
    if self.is_git_version(entry['resolved']):
                           ~~~~~^^^^^^^^^^^^
KeyError: 'resolved'
```

**Comment by vixalien** [comment]
have this error too. did you manage to fix it?

**Comment by marc0x1** [comment]
> have this error too. did you manage to fix it?

Sadly no

**Comment by jwillikers** [comment]
Same issue

**Comment by daviddavo** [comment]
Tried both with Python 3.11 and 3.10. Same issue here.

**Comment by daviddavo** [comment]
I added some prints to the file to know which package failed. It was a package in a folder, with an entry like this:

```yarn
tldraw-logseq@../apps/tldraw-logseq:
  version "0.0.0-dev"
```

It really doesn't have a `resolved` (nor `integrity`) field

**Comment by bbhtt** [comment]
If this is still reproducible, I need a specific lockfile to reproduce it. Linking to the git repo is not sufficient, it is a moving target as time passes.
