### ISSUE TITLE
Cannot install flatpak-node-generator

### ISSUE THREAD

**Issue by zadam** [flatpak/flatpak-builder-tools#359]
### flatpak-builder version

1.2.3

### Linux distribution and version

Ubuntu 23.04

### Affected flatpak-builder tool

node/flatpak-node-generator.py

### Description

Hi, the recommended way to install flatpak-node-generator is this (in the clone repository):

```
$ pipx install .
```

But it just errors out:

```
~/tmp/flatpak-builder-tools/node$ pipx install .
Traceback (most recent call last):
File "/usr/bin/pipx", line 8, in <module>
sys.exit(cli())
^^^^^
File "/usr/lib/python3/dist-packages/pipx/main.py", line 819, in cli
return run_pipx_command(parsed_pipx_args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/pipx/main.py", line 202, in run_pipx_command
return commands.install(
^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/pipx/commands/install.py", line 30, in install
package_name = package_name_from_spec(
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/pipx/commands/common.py", line 333, in package_name_from_spec
package_name = venv.install_package_no_deps(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/pipx/venv.py", line 268, in install_package_no_deps
old_package_set = self.list_installed_packages()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/pipx/venv.py", line 348, in list_installed_packages
pip_list = json.loads(cmd_run.stdout.strip())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The error is not particularly helpful, does anyone know what might be the problem?

**Comment by refi64** [comment]
This sounds a bit like your pip installation might be a bit broken, so it's failing to print the JSON output that pipx expects. If you pass `--verbose` to pipx, you can see what command it's running that's failing, and then run it yourself to inspect the output.

**Comment by zadam** [comment]
Thanks, that helped track it down a bit. Found https://github.com/pypa/pipx/issues/393 and https://github.com/pypa/pipx/issues/386

I uninstalled pipx, `rm -r ~/.local/pipx`, installed pipx again and it started working.

**Comment by hadess** [comment]
Ran into this as well, this should be mentioned in the README.

**Comment by hadess** [comment]
> I uninstalled pipx, `rm -r ~/.local/pipx`, installed pipx again and it started working.

I just `rm -rf ~/.local/pipx` to work-around the problem.
