### ISSUE TITLE
cargo generator cant seem to find `build-dependencies`

### ISSUE THREAD

**Issue by ImUrX** [flatpak/flatpak-builder-tools#367]
### flatpak-builder version

1.2.3

### Linux distribution and version

NixOS 23.11.20230830.e7f38be

### Affected flatpak-builder tool

cargo/flatpak-cargo-generator.py

### Source repository URL

https://github.com/SlimeVR/SlimeVR-Server.git

### Flatpak-builder manifest URL

https://github.com/flathub/dev.slimevr.SlimeVR.git

### Description

I'm trying to generate a sources.json and it seems its trying to find `build-dependencies` item when it doesn't exist, I'm really unsure for the reason. I saw that I had a repeated dependency and fixed it but it still happens.

**Comment by madoka773** [comment]
```
⬢[root@toolbox io.github.keiko233.clash-nyanpasu]# ../../../flatpak-builder-tools/cargo/flatpak-cargo-generator.py ../../../clash-rs/Cargo.lock -o clash-rs/clash-rscargo-sources.json
INFO:root:Loading packages from https://github.com/watfaq/boring
INFO:root:Adding package boring from https://github.com/watfaq/boring
INFO:root:Adding package boring-sys from https://github.com/watfaq/boring
INFO:root:Adding package hyper-boring from https://github.com/watfaq/boring
INFO:root:Loading packages from https://github.com/watfaq/netstack-lwip
INFO:root:Adding package netstack-lwip from https://github.com/watfaq/netstack-lwip
INFO:root:Adding package tokio-boring from https://github.com/watfaq/boring
INFO:root:Loading packages from https://github.com/watfaq/rust-tun
INFO:root:Adding package tun from https://github.com/watfaq/rust-tun
Traceback (most recent call last):
  File "/root/Projects/repos/manifests/io.github.keiko233.clash-nyanpasu/../../../flatpak-builder-tools/cargo/flatpak-cargo-generator.py", line 449, in <module>
    main()
  File "/root/Projects/repos/manifests/io.github.keiko233.clash-nyanpasu/../../../flatpak-builder-tools/cargo/flatpak-cargo-generator.py", line 442, in main
    generated_sources = asyncio.run(generate_sources(load_toml(args.cargo_lock),
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/Projects/repos/manifests/io.github.keiko233.clash-nyanpasu/../../../flatpak-builder-tools/cargo/flatpak-cargo-generator.py", line 396, in generate_sources
    for pkg in await asyncio.gather(*pkg_coros):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/Projects/repos/manifests/io.github.keiko233.clash-nyanpasu/../../../flatpak-builder-tools/cargo/flatpak-cargo-generator.py", line 346, in get_package_sources
    return await get_git_package_sources(package, git_repos)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/Projects/repos/manifests/io.github.keiko233.clash-nyanpasu/../../../flatpak-builder-tools/cargo/flatpak-cargo-generator.py", line 316, in get_git_package_sources
    'contents': toml.dumps(git_pkg.normalized),
                           ^^^^^^^^^^^^^^^^^^
  File "/root/Projects/repos/manifests/io.github.keiko233.clash-nyanpasu/../../../flatpak-builder-tools/cargo/flatpak-cargo-generator.py", line 139, in normalized
    package[section_key][key] = self.workspace[section_key][key]
                                ~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'dev-dependencies'
```

me too

**Comment by madoka773** [comment]
any workaround?

**Comment by zecakeh** [comment]
I am not sure I understand when the error happens. Does it happen when you run flatpak-cargo-generator, or later when you are trying to build the flatpak with the generated sources?

Is it possible to have logs about the operation? Also it is possible to link to a particular revision of a Cargo.lock file where this is reproducible? I tried the projects linked here but the script ran without any error.

**Comment by bbhtt** [comment]
The error was:

```
Traceback (most recent call last):
  File "/home/bbhtt/Git/github/flatpak-builder-tools/cargo/flatpak-cargo-generator.py", line 449, in <module>
    main()
    ~~~~^^
  File "/home/bbhtt/Git/github/flatpak-builder-tools/cargo/flatpak-cargo-generator.py", line 442, in main
    generated_sources = asyncio.run(generate_sources(load_toml(args.cargo_lock),
                                    git_tarballs=args.git_tarballs))
  File "/usr/lib64/python3.13/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/usr/lib64/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/lib64/python3.13/asyncio/base_events.py", line 719, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/home/bbhtt/Git/github/flatpak-builder-tools/cargo/flatpak-cargo-generator.py", line 396, in generate_sources
    for pkg in await asyncio.gather(*pkg_coros):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bbhtt/Git/github/flatpak-builder-tools/cargo/flatpak-cargo-generator.py", line 346, in get_package_sources
    return await get_git_package_sources(package, git_repos)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bbhtt/Git/github/flatpak-builder-tools/cargo/flatpak-cargo-generator.py", line 316, in get_git_package_sources
    'contents': toml.dumps(git_pkg.normalized),
                           ^^^^^^^^^^^^^^^^^^
  File "/home/bbhtt/Git/github/flatpak-builder-tools/cargo/flatpak-cargo-generator.py", line 139, in normalized
    package[section_key][key] = self.workspace[section_key][key]
                                ~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'build-dependencies'
```

It was fixed by https://github.com/flatpak/flatpak-builder-tools/commit/6cee2f9c5b628a6c60f5bf35317eaf81066cd3bb
