### ISSUE TITLE
cargo: TomlDecodeError when attempting to parse Cargo.lock for rustdesk

### ISSUE THREAD

**Issue by joshua-stone** [flatpak/flatpak-builder-tools#384]
### flatpak-builder version

1.3.1

### Linux distribution and version

Fedora 39

### Affected flatpak-builder tool

cargo/flatpak-cargo-generator.py

### flatpak-builder tool cli args

python3 ./flatpak-cargo-generator.py Cargo.lock --output generated-sources.json

### Source repository URL

https://github.com/rustdesk/rustdesk

### Flatpak-builder manifest URL

https://gist.github.com/joshua-stone/d0e706b8772336f760de174424475f71

### Description

Running `python3 ./flatpak-cargo-generator.py Cargo.lock --output generated-sources.json` for rustdesk will result in the the following error:

```
toml.decoder.TomlDecodeError: An implicitly defined table can't be an array (line 64 column 1 char 1903)
```

If I remove the `cacao` package from Cargo.lock, then sources will successfully generate:

```toml
[[package]]
name = "cacao"
version = "0.4.0-beta2"
source = "git+https://github.com/clslaid/cacao?branch=feat/set-file-urls#05e1536b0b43aaae308ec72c0eed703e875b7b95"
dependencies = [
 "bitmask-enum",
 "block2",
 "core-foundation 0.9.3 (git+https://github.com/madsmtm/core-foundation-rs.git?rev=7d593d016175755e492a92ef89edca68ac3bd5cd)",
 "core-graphics 0.23.1",
 "dispatch",
 "lazy_static",
 "libc",
 "objc2",
 "os_info",
 "percent-encoding",
 "url",
]
```

**Comment by bbhtt** [comment]
https://github.com/ryanmcgrath/cacao/blob/094ed59a04f504913d276e6b091db0172f71cf12/Cargo.toml is the source of the invalid Cargo.toml here. It's a dependency of rustdesk. 

```sh
python -c "import requests, toml; cargo_data = toml.loads(requests.get('https://raw.githubusercontent.com/ryanmcgrath/cacao/094ed59a04f504913d276e6b091db0172f71cf12/Cargo.toml').text)"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import requests, toml; cargo_data = toml.loads(requests.get('https://raw.githubusercontent.com/ryanmcgrath/cacao/094ed59a04f504913d276e6b091db0172f71cf12/Cargo.toml').text)
                                        ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/toml/decoder.py", line 471, in loads
    raise TomlDecodeError("An implicitly defined "
                          "table can't be an array",
                          original, pos)
toml.decoder.TomlDecodeError: An implicitly defined table can't be an array (line 63 column 1 char 1876)
```


It's using the same table key as a regular table and an array of tables `example`. Fix would be to rename one of them, for example

```patch
diff --git a/Cargo.toml b/Cargo.toml
index 639e96c..584aeec 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -49,7 +49,7 @@ user-notifications = ["uuid"]
 webview = ["infer"]
 webview-downloading-macos = []
 
-[package.metadata.bundle.example.ios-beta]
+[package.metadata.bundle.examples.ios-beta]
 name = "ios-beta"
 identifier = "com.cacao.ios-test"
 category = "Developer Tool"
```

You should open an issue there.
