### ISSUE TITLE
[node] NotImplementedError: Don't know how to handle package  in package-lock.json

### ISSUE THREAD

**Issue by saccarosium** [flatpak/flatpak-builder-tools#391]
### flatpak-builder version

1.4.0

### Linux distribution and version

Debian Testing (13)

### Affected flatpak-builder tool

node/flatpak-node-generator.py

### Description

When trying to generate a `generated-sources.json` from a `package.json` gives the following error: `NotImplementedError: Don't know how to handle package  in package-lock.json`.

- Node version: `v18.19.0`
<details><summary>Full Error</summary>
<p>

```
Reading packages from lockfiles...
Traceback (most recent call last):
  File "/home/sacca/.local/bin/flatpak-node-generator", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/sacca/.local/share/pipx/venvs/flatpak-node-generator/lib/python3.11/site-packages/flatpak_node_generator/main.py", line 277, in main
    asyncio.run(_async_main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/sacca/.local/share/pipx/venvs/flatpak-node-generator/lib/python3.11/site-packages/flatpak_node_generator/main.py", line 198, in _async_main
    packages.update(lockfile_provider.process_lockfile(lockfile))
  File "/home/sacca/.local/share/pipx/venvs/flatpak-node-generator/lib/python3.11/site-packages/flatpak_node_generator/providers/npm.py", line 166, in process_lockfile
    yield from self._process_packages_v2(lockfile, data)
  File "/home/sacca/.local/share/pipx/venvs/flatpak-node-generator/lib/python3.11/site-packages/flatpak_node_generator/providers/npm.py", line 138, in _process_packages_v2
    raise NotImplementedError(
NotImplementedError: Don't know how to handle package  in package-lock.json
```

</p>
</details>

**Comment by hfiguiere** [comment]
> ### Affected flatpak-builder tool
> 
> cargo/flatpak-cargo-generator.py

Is this correct? Since the problem is with `package-lock.json`

**Comment by saccarosium** [comment]
> > ### Affected flatpak-builder tool
> > cargo/flatpak-cargo-generator.py
> 
> Is this correct? Since the problem is with `package-lock.json`

Nope I had problems with the picker.

**Comment by Ian2020** [comment]
Hi this "not implemented" exception has been address in my PR below with full support for npm git sources. If this is still an issue please try my code there and let me know if any issues:

https://github.com/flatpak/flatpak-builder-tools/pull/382
