### ISSUE TITLE
npm: Electron v3.0.11-arm fails

### ISSUE THREAD

**Issue by muelli** [flatpak/flatpak-builder-tools#40]
I'm getting this exception

```
flatpak-npm-generator.py --recursive package-lock.json 
Scanning "package-lock.json" 
Traceback (most recent call last):
  File "flatpak-npm-generator.py", line 259, in <module>
    main()
  File "flatpak-npm-generator.py", line 239, in main
    s = getModuleSources(root, None, seen, include_devel=include_devel, npm3=npm3)
  File "flatpak-npm-generator.py", line 195, in getModuleSources
    child_sources = getModuleSources(deps[dep], seen, include_devel=include_devel)
  File "flatpak-npm-generator.py", line 182, in getModuleSources
    "sha256": shasums[basename],
KeyError: 'electron-v3.0.11-linux-arm.zip'
```

with this package-lock.json file: 
[package-lock.json.log](https://github.com/flatpak/flatpak-builder-tools/files/2674376/package-lock.json.log)

**Comment by scx** [comment]
Same issue here:
```
$ python ~/software/flatpak-builder-tools/flatpak-builder-tools/npm/flatpak-npm-generator.py package-lock.json 
Scanning "package-lock.json" 
Traceback (most recent call last):
  File "/home/scx/software/flatpak-builder-tools/flatpak-builder-tools/npm/flatpak-npm-generator.py", line 259, in <module>
    main()
  File "/home/scx/software/flatpak-builder-tools/flatpak-builder-tools/npm/flatpak-npm-generator.py", line 239, in main
    s = getModuleSources(root, None, seen, include_devel=include_devel, npm3=npm3)
  File "/home/scx/software/flatpak-builder-tools/flatpak-builder-tools/npm/flatpak-npm-generator.py", line 195, in getModuleSources
    child_sources = getModuleSources(deps[dep], seen, include_devel=include_devel)
  File "/home/scx/software/flatpak-builder-tools/flatpak-builder-tools/npm/flatpak-npm-generator.py", line 182, in getModuleSources
    "sha256": shasums[basename],
KeyError: 'electron-v3.0.8-linux-arm.zip'
```

Probably related to:
https://github.com/electron/electron/issues/13745#issuecomment-406495689
