### ISSUE TITLE
flatpak-pip-generator: fails to install poetry

### ISSUE THREAD

**Issue by danyeaw** [flatpak/flatpak-builder-tools#50]
[Poetry](https://poetry.eustace.io/) is a more modern way to manage package dependencies with Python. It currently doesn't work with flatpak-pip-generator.

```
(Gaphor) dan@dan-Librem-13-v2:~/Projects/gaphor$ python flatpak/pip-generator.py poetry
Collecting poetry
  Using cached https://files.pythonhosted.org/packages/75/44/824cee51be9ee1f2c28042a58591a36cef0c85f688f7ddc5b088af26d50a/poetry-0.12.11.tar.gz
  Saved /tmp/pip-generator-python3-poetry-gu40j27d/poetry-0.12.11.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting pkginfo<2.0,>=1.4 (from poetry)
  Using cached https://files.pythonhosted.org/packages/6c/04/fd6683d24581894be8b25bc8c68ac7a0a73bf0c4d74b888ac5fe9a28e77f/pkginfo-1.5.0.1.tar.gz
  Saved /tmp/pip-generator-python3-poetry-gu40j27d/pkginfo-1.5.0.1.tar.gz
Collecting requests-toolbelt<0.9.0,>=0.8.0 (from poetry)
  Using cached https://files.pythonhosted.org/packages/86/f9/e80fa23edca6c554f1994040064760c12b51daff54b55f9e379e899cd3d4/requests-toolbelt-0.8.0.tar.gz
  Saved /tmp/pip-generator-python3-poetry-gu40j27d/requests-toolbelt-0.8.0.tar.gz
Collecting tomlkit<0.6.0,>=0.5.1 (from poetry)
  Using cached https://files.pythonhosted.org/packages/f7/f7/bbd9213bfe76cb7821c897f9ed74877fd74993b4ca2fe9513eb5a31030f9/tomlkit-0.5.3.tar.gz
  Saved /tmp/pip-generator-python3-poetry-gu40j27d/tomlkit-0.5.3.tar.gz
  Installing build dependencies ... error
  Complete output from command /home/dan/Projects/gaphor/.venv/bin/python3 /home/dan/Projects/gaphor/.venv/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-bwjf36dl/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- poetry>=0.12a3:
  Collecting poetry>=0.12a3
    Using cached https://files.pythonhosted.org/packages/93/8a/270aa699a07405df9b260f9192eec043cf486b4b49fafd7ebcee09cb2cc5/poetry-1.0.0a2.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Collecting requests<3.0,>=2.18 (from poetry>=0.12a3)
    Using cached https://files.pythonhosted.org/packages/52/2c/514e4ac25da2b08ca5a464c50463682126385c4272c18193876e91f4bc38/requests-2.21.0.tar.gz
  Collecting jsonschema<4.0,>=3.0a3 (from poetry>=0.12a3)
    Using cached https://files.pythonhosted.org/packages/1f/7f/a020327823b9c405ee6f85ab3053ff171e10801b19cfe55c78bb0b3810e7/jsonschema-3.0.1.tar.gz
  Collecting pyrsistent<0.15.0,>=0.14.2 (from poetry>=0.12a3)
    Using cached https://files.pythonhosted.org/packages/8c/46/4e93ab8a379d7efe93f20a0fb8a27bdfe88942cc954ab0210c3164e783e0/pyrsistent-0.14.11.tar.gz
  Collecting html5lib<2.0,>=1.0 (from poetry>=0.12a3)
    Using cached https://files.pythonhosted.org/packages/85/3e/cf449cf1b5004e87510b9368e7a5f1acd8831c2d6691edd3c62a0823f98f/html5lib-1.0.1.tar.gz
  Collecting cachecontrol[filecache]<0.13.0,>=0.12.4 (from poetry>=0.12a3)
    Using cached https://files.pythonhosted.org/packages/5e/f0/2c193ed1f17c97ae539da7e1c2d48b80d8cccb1917163b26a91ca4355aa6/CacheControl-0.12.5.tar.gz
  Collecting pyparsing<3.0,>=2.2 (from poetry>=0.12a3)
    Using cached https://files.pythonhosted.org/packages/b9/b8/6b32b3e84014148dcd60dd05795e35c2e7f4b72f918616c61fdce83d27fc/pyparsing-2.3.1.tar.gz
  Collecting requests-toolbelt<0.9.0,>=0.8.0 (from poetry>=0.12a3)
    Using cached https://files.pythonhosted.org/packages/86/f9/e80fa23edca6c554f1994040064760c12b51daff54b55f9e379e899cd3d4/requests-toolbelt-0.8.0.tar.gz
  Collecting shellingham<2.0,>=1.1 (from poetry>=0.12a3)
    Using cached https://files.pythonhosted.org/packages/04/47/c3f0b5fce44827d011f7f4b8831dd20984a228d7a7f46d4d45f1aaa6fd90/shellingham-1.2.8.tar.gz
  Collecting tomlkit<0.6.0,>=0.5.1 (from poetry>=0.12a3)
    Using cached https://files.pythonhosted.org/packages/f7/f7/bbd9213bfe76cb7821c897f9ed74877fd74993b4ca2fe9513eb5a31030f9/tomlkit-0.5.3.tar.gz
  Exception:
  Traceback (most recent call last):
    File "/home/dan/Projects/gaphor/.venv/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 179, in main
      status = self.run(options, args)
    File "/home/dan/Projects/gaphor/.venv/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 315, in run
      resolver.resolve(requirement_set)
    File "/home/dan/Projects/gaphor/.venv/lib/python3.7/site-packages/pip/_internal/resolve.py", line 131, in resolve
      self._resolve_one(requirement_set, req)
    File "/home/dan/Projects/gaphor/.venv/lib/python3.7/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
      abstract_dist = self._get_abstract_dist_for(req_to_install)
    File "/home/dan/Projects/gaphor/.venv/lib/python3.7/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
      self.require_hashes
    File "/home/dan/Projects/gaphor/.venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 348, in prepare_linked_requirement
      with self.req_tracker.track(req):
    File "/home/dan/.pyenv/versions/3.7.1/lib/python3.7/contextlib.py", line 112, in __enter__
      return next(self.gen)
    File "/home/dan/Projects/gaphor/.venv/lib/python3.7/site-packages/pip/_internal/req/req_tracker.py", line 86, in track
      self.add(req)
    File "/home/dan/Projects/gaphor/.venv/lib/python3.7/site-packages/pip/_internal/req/req_tracker.py", line 55, in add
      % (link, fp.read()))
  LookupError: https://files.pythonhosted.org/packages/f7/f7/bbd9213bfe76cb7821c897f9ed74877fd74993b4ca2fe9513eb5a31030f9/tomlkit-0.5.3.tar.gz#sha256=d6506342615d051bc961f70bfcfa3d29b6616cc08a3ddfd4bc24196f16fd4ec2 (from https://pypi.org/simple/tomlkit/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*) is already being built: tomlkit<0.6.0,>=0.5.1 from https://files.pythonhosted.org/packages/f7/f7/bbd9213bfe76cb7821c897f9ed74877fd74993b4ca2fe9513eb5a31030f9/tomlkit-0.5.3.tar.gz#sha256=d6506342615d051bc961f70bfcfa3d29b6616cc08a3ddfd4bc24196f16fd4ec2 (from poetry)
  
  ----------------------------------------
Command "/home/dan/Projects/gaphor/.venv/bin/python3 /home/dan/Projects/gaphor/.venv/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-bwjf36dl/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- poetry>=0.12a3" failed with error code 2 in None
Traceback (most recent call last):
  File "flatpak/pip-generator.py", line 75, in <module>
    ] + opts.packages, check=True)
  File "/home/dan/.pyenv/versions/3.7.1/lib/python3.7/subprocess.py", line 481, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pip3', 'download', '--dest', '/tmp/pip-generator-python3-poetry-gu40j27d', '--no-binary', ':all:', 'poetry']' returned non-zero exit status 1.
```
I can get around some of these errors by remove the `--no-binary :all:` option from pip-generator, but then I get 404 errors for some of the packages.
```
(Gaphor) dan@dan-Librem-13-v2:~/Projects/gaphor$ python flatpak/pip-generator.py poetry
Collecting poetry
  Using cached https://files.pythonhosted.org/packages/64/2d/8221b951085667039cc45b4a9013f7cd4efd34f13dfcca04a90ed4046c72/poetry-0.12.11-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-poetry-gx0pjjs3/poetry-0.12.11-py2.py3-none-any.whl
Collecting cachecontrol[filecache]<0.13.0,>=0.12.4 (from poetry)
  Using cached https://files.pythonhosted.org/packages/5e/f0/2c193ed1f17c97ae539da7e1c2d48b80d8cccb1917163b26a91ca4355aa6/CacheControl-0.12.5.tar.gz
  Saved /tmp/pip-generator-python3-poetry-gx0pjjs3/CacheControl-0.12.5.tar.gz
Collecting cachy<0.3,>=0.2 (from poetry)
  Using cached https://files.pythonhosted.org/packages/26/37/8ce3e7b330078b6797a34e79a80a8ad6935e404a3b903765417182c9ce19/cachy-0.2.0-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-poetry-gx0pjjs3/cachy-0.2.0-py2.py3-none-any.whl
Collecting requests-toolbelt<0.9.0,>=0.8.0 (from poetry)
  Using cached https://files.pythonhosted.org/packages/97/8a/d710f792d6f6ecc089c5e55b66e66c3f2f35516a1ede5a8f54c13350ffb0/requests_toolbelt-0.8.0-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-poetry-gx0pjjs3/requests_toolbelt-0.8.0-py2.py3-none-any.whl
Collecting shellingham<2.0,>=1.1 (from poetry)
  Using cached https://files.pythonhosted.org/packages/74/b7/36cdb13e9ecf1e9584cd78a47a1853831cf8817da3438aeec550cd83619c/shellingham-1.2.8-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-poetry-gx0pjjs3/shellingham-1.2.8-py2.py3-none-any.whl
Collecting pyparsing<3.0,>=2.2 (from poetry)
  Using cached https://files.pythonhosted.org/packages/de/0a/001be530836743d8be6c2d85069f46fecf84ac6c18c7f5fb8125ee11d854/pyparsing-2.3.1-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-poetry-gx0pjjs3/pyparsing-2.3.1-py2.py3-none-any.whl
Collecting html5lib<2.0,>=1.0 (from poetry)
  Using cached https://files.pythonhosted.org/packages/a5/62/bbd2be0e7943ec8504b517e62bab011b4946e1258842bc159e5dfde15b96/html5lib-1.0.1-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-poetry-gx0pjjs3/html5lib-1.0.1-py2.py3-none-any.whl
Collecting cleo<0.7.0,>=0.6.7 (from poetry)
  Using cached https://files.pythonhosted.org/packages/a7/b9/270301a3a87587f09bc3985973f2e362ffa45fa5fcd5128501516b2f5e31/cleo-0.6.8-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-poetry-gx0pjjs3/cleo-0.6.8-py2.py3-none-any.whl
Collecting pkginfo<2.0,>=1.4 (from poetry)
  Using cached https://files.pythonhosted.org/packages/e6/d5/451b913307b478c49eb29084916639dc53a88489b993530fed0a66bab8b9/pkginfo-1.5.0.1-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-poetry-gx0pjjs3/pkginfo-1.5.0.1-py2.py3-none-any.whl
Collecting requests<3.0,>=2.18 (from poetry)
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-poetry-gx0pjjs3/requests-2.21.0-py2.py3-none-any.whl
Collecting jsonschema<4.0,>=3.0a3 (from poetry)
  Using cached https://files.pythonhosted.org/packages/aa/69/df679dfbdd051568b53c38ec8152a3ab6bc533434fc7ed11ab034bf5e82f/jsonschema-3.0.1-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-poetry-gx0pjjs3/jsonschema-3.0.1-py2.py3-none-any.whl
Collecting pyrsistent<0.15.0,>=0.14.2 (from poetry)
  Using cached https://files.pythonhosted.org/packages/8c/46/4e93ab8a379d7efe93f20a0fb8a27bdfe88942cc954ab0210c3164e783e0/pyrsistent-0.14.11.tar.gz
  Saved /tmp/pip-generator-python3-poetry-gx0pjjs3/pyrsistent-0.14.11.tar.gz
Collecting tomlkit<0.6.0,>=0.5.1 (from poetry)
  Using cached https://files.pythonhosted.org/packages/71/c6/06c014b92cc48270765d6a9418d82239b158d8a9b69e031b0e2c6598740b/tomlkit-0.5.3-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-poetry-gx0pjjs3/tomlkit-0.5.3-py2.py3-none-any.whl
Collecting msgpack (from cachecontrol[filecache]<0.13.0,>=0.12.4->poetry)
  Using cached https://files.pythonhosted.org/packages/a8/7b/630049fc4af9e68a625738612edc264ce7cb586c5001a2d4d2209a4f61c1/msgpack-0.6.1-cp37-cp37m-manylinux1_x86_64.whl
  Saved /tmp/pip-generator-python3-poetry-gx0pjjs3/msgpack-0.6.1-cp37-cp37m-manylinux1_x86_64.whl
Collecting lockfile>=0.9 (from cachecontrol[filecache]<0.13.0,>=0.12.4->poetry)
  Using cached https://files.pythonhosted.org/packages/c8/22/9460e311f340cb62d26a38c419b1381b8593b0bb6b5d1f056938b086d362/lockfile-0.12.2-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-poetry-gx0pjjs3/lockfile-0.12.2-py2.py3-none-any.whl
Collecting webencodings (from html5lib<2.0,>=1.0->poetry)
  Using cached https://files.pythonhosted.org/packages/f4/24/2a3e3df732393fed8b3ebf2ec078f05546de641fe1b667ee316ec1dcf3b7/webencodings-0.5.1-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-poetry-gx0pjjs3/webencodings-0.5.1-py2.py3-none-any.whl
Collecting six>=1.9 (from html5lib<2.0,>=1.0->poetry)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-poetry-gx0pjjs3/six-1.12.0-py2.py3-none-any.whl
Collecting pastel<0.2.0,>=0.1.0 (from cleo<0.7.0,>=0.6.7->poetry)
  Using cached https://files.pythonhosted.org/packages/9b/7e/7d701686013c0d7dae62e0977467232a6adc2e562c23878eb3cd4f97d02e/pastel-0.1.0-py3-none-any.whl
  Saved /tmp/pip-generator-python3-poetry-gx0pjjs3/pastel-0.1.0-py3-none-any.whl
Collecting pylev<2.0,>=1.3 (from cleo<0.7.0,>=0.6.7->poetry)
  Using cached https://files.pythonhosted.org/packages/40/1c/7dff1d242bf1e19f9c6202f0ba4e6fd18cc7ecb8bc85b17b2d16c806e228/pylev-1.3.0-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-poetry-gx0pjjs3/pylev-1.3.0-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests<3.0,>=2.18->poetry)
  Using cached https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-poetry-gx0pjjs3/certifi-2018.11.29-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests<3.0,>=2.18->poetry)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-poetry-gx0pjjs3/idna-2.8-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests<3.0,>=2.18->poetry)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-poetry-gx0pjjs3/urllib3-1.24.1-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests<3.0,>=2.18->poetry)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-poetry-gx0pjjs3/chardet-3.0.4-py2.py3-none-any.whl
Collecting setuptools (from jsonschema<4.0,>=3.0a3->poetry)
  Using cached https://files.pythonhosted.org/packages/d1/6a/4b2fcefd2ea0868810e92d519dacac1ddc64a2e53ba9e3422c3b62b378a6/setuptools-40.8.0-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-poetry-gx0pjjs3/setuptools-40.8.0-py2.py3-none-any.whl
Collecting attrs>=17.4.0 (from jsonschema<4.0,>=3.0a3->poetry)
  Using cached https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
  Saved /tmp/pip-generator-python3-poetry-gx0pjjs3/attrs-19.1.0-py2.py3-none-any.whl
Successfully downloaded poetry cachecontrol cachy requests-toolbelt shellingham pyparsing html5lib cleo pkginfo requests jsonschema pyrsistent tomlkit msgpack lockfile webencodings six pastel pylev certifi idna urllib3 chardet setuptools attrs
Generating hash for /tmp/pip-generator-python3-poetry-gx0pjjs3/idna-2.8-py2.py3-none-any.whl
Extracting download url for idna-2.8-py2.py3-none
Traceback (most recent call last):
  File "flatpak/pip-generator.py", line 103, in <module>
    url = get_pypi_url(name, filename)
  File "flatpak/pip-generator.py", line 32, in get_pypi_url
    with urllib.request.urlopen(url) as response:
  File "/home/dan/.pyenv/versions/3.7.1/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/dan/.pyenv/versions/3.7.1/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/dan/.pyenv/versions/3.7.1/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/dan/.pyenv/versions/3.7.1/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/home/dan/.pyenv/versions/3.7.1/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/dan/.pyenv/versions/3.7.1/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/home/dan/.pyenv/versions/3.7.1/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/dan/.pyenv/versions/3.7.1/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/dan/.pyenv/versions/3.7.1/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/home/dan/.pyenv/versions/3.7.1/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/dan/.pyenv/versions/3.7.1/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/home/dan/.pyenv/versions/3.7.1/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/dan/.pyenv/versions/3.7.1/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/dan/.pyenv/versions/3.7.1/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/dan/.pyenv/versions/3.7.1/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/dan/.pyenv/versions/3.7.1/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```
One option might be to generate the json file from the poetry.lock file, I understand that is more like how the yarn builder-tool works.

**Comment by TingPing** [comment]
> One option might be to generate the json file from the poetry.lock file,

Yes that has been something on the todo list if somebody is interested in it.

**Comment by danyeaw** [comment]
@TingPing I'll give it a shot :+1:

**Comment by bilelmoussaoui** [comment]
Can be closed.
