### ISSUE TITLE
cargo: crash with checksum KeyError

### ISSUE THREAD

**Issue by gdesmott** [flatpak/flatpak-builder-tools#66]
Tried to run the generator with `Cargo.lock` from https://github.com/gdesmott/karapulse 

```
$ ./flatpak-cargo-generator.py ~/dev/rust/karapulse/Cargo.lock
Traceback (most recent call last):
  File "./flatpak-cargo-generator.py", line 81, in <module>
    main()
  File "./flatpak-cargo-generator.py", line 76, in main
    generated_sources = generate_sources(load_cargo_lock(args.cargo_lock))
  File "./flatpak-cargo-generator.py", line 38, in generate_sources
    checksum = metadata[f'checksum {name} {version} ({source})']
KeyError: 'checksum gst-plugin-cdg 0.5.0 (git+https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs?branch=0.5#43aeb840e59b6b019789f80714459f9bff5f954d)'
```

**Comment by gdesmott** [comment]
The problem is that I have this in `Cargo.toml`:

```toml
gst-plugin-cdg = { git = "https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs", branch="0.5", optional=true }
```
resulting in this in `Cargo.lock`:

```toml
[[package]]
name = "gst-plugin-cdg"
version = "0.5.0"
source = "git+https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs?branch=0.5#43aeb840e59b6b019789f80714459f9bff5f954d"

[metadata]
"checksum gst-plugin-cdg 0.5.0 (git+https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs?branch=0.5)" = "<none>"
```

As you can see the source fields don't match as one is suffixed by `#COMMIT_ID`, resulting in the `KeyError` exception. Also the metadata is not pointing to any commit id.

I quickly hacked this workaround which seems to work but it's pretty horrible so let me know if you have a better idea:

```patch
-            checksum = metadata[f'checksum {name} {version} ({source})']
+            if source[-41] == '#':
+                checksum = source[-40:]
+                source = source[:-41]
+            else:
+               checksum = metadata[f'checksum {name} {version} ({source})']
```

**Comment by gdesmott** [comment]
Actually that doesn't work as the generated file points to a not existing crate:

```
    {
        "type": "file",
        "url": "https://static.crates.io/crates/gst-plugin-cdg/gst-plugin-cdg-0.5.0.crate",
        "sha256": "43aeb840e59b6b019789f80714459f9bff5f954d",
        "dest": "cargo/vendor",
        "dest-filename": "gst-plugin-cdg-0.5.0.crate"
    },
```

But won't we have this problem with any Cargo file using unreleased dependencies? Is the generator usable only if all the deps are in released crates?
