### ISSUE TITLE
[pip] fails with feedparser package (regression)

### ISSUE THREAD

**Issue by lazka** [flatpak/flatpak-builder-tools#73]
Tried updating the submodule today, which led to this:

```python
Collecting feedparser
  Using cached https://files.pythonhosted.org/packages/91/d8/7d37fec71ff7c9dbcdd80d2b48bcdd86d6af502156fc93846fb0102cb2c4/feedparser-5.2.1.tar.bz2
  Saved /tmp/pip-generator-python3-feedparser-l82ahg_k/feedparser-5.2.1.tar.bz2
Successfully downloaded feedparser
Traceback (most recent call last):
  File "flatpak-builder-tools/pip/flatpak-pip-generator", line 132, in <module>
    name = get_package_name(filename)
  File "flatpak-builder-tools/pip/flatpak-pip-generator", line 58, in get_package_name
    'Downloaded filename: {} does not end with gz, zip, or whl'.format(filename)
Exception: Downloaded filename: feedparser-5.2.1.tar.bz2 does not end with gz, zip, or whl
```

Looking at distutils code (https://github.com/python/cpython/blob/c5d5dfdb223efb0e668e3f317d31b8b70ae96aa6/Lib/distutils/archive_util.py), `xz` is also possible.

**Comment by lazka** [comment]
Thanks!
