### ISSUE TITLE
pip-generator fails for ipykernel

### ISSUE THREAD

**Issue by cvfosammmm** [flatpak/flatpak-builder-tools#89]
After labouring for a while it fails with the following output. This is a blocker regards releasing my app as a flatpak, so it would be nice if it could be fixed.

```  Collecting pyzmq>=13 (from jupyter_client)
    Using cached https://files.pythonhosted.org/packages/3c/83/7ecbe9b762829f589fa9734026e0ccb63cb128fe5615ae1698f65df72bfe/pyzmq-18.1.1.tar.gz
  Collecting tornado>=4.1 (from jupyter_client)
    Using cached https://files.pythonhosted.org/packages/30/78/2d2823598496127b21423baffaa186b668f73cd91887fcef78b6eade136b/tornado-6.0.3.tar.gz
  Collecting parso>=0.5.2 (from jedi>=0.10->ipython>=5)
    Using cached https://files.pythonhosted.org/packages/e0/a2/3786c568fc8e9f64b9f7143e4c3904e61a8c5cb17260f22a6a3019d80c02/parso-0.5.2.tar.gz
  Collecting ptyprocess>=0.5 (from pexpect->ipython>=5)
    Using cached https://files.pythonhosted.org/packages/7d/2d/e4b8733cf79b7309d84c9081a4ab558c89d8c89da5961bf4ddb050ca1ce0/ptyprocess-0.6.0.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'error'
    Complete output from command /usr/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-pu0sb232 --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- flit:
    Collecting flit
      Using cached https://files.pythonhosted.org/packages/35/87/a92625dc5c81cf1608553b27b5c216bdc1e678ea6738a3a8a69ee2e5fb51/flit-2.2.0.tar.gz
      Installing build dependencies: started
      Installing build dependencies: finished with status 'error'
      Complete output from command /usr/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-pqaygza0 --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- "flit_core >=2.2.0,<3":
      Collecting flit_core<3,>=2.2.0
        Using cached https://files.pythonhosted.org/packages/77/72/5dda5dc417a4e702e0d7e4a77e9802792a0e4a2daec2aeed915ead7db477/flit_core-2.2.0.tar.gz
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
          Complete output from command python setup.py egg_info:
          Traceback (most recent call last):
            File "<string>", line 1, in <module>
            File "/usr/lib/python3.7/tokenize.py", line 447, in open
              buffer = _builtin_open(filename, 'rb')
          FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-ommvg2hw/flit-core/setup.py'
  
          ----------------------------------------
      Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ommvg2hw/flit-core/
  
      ----------------------------------------
    Command "/usr/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-pqaygza0 --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- "flit_core >=2.2.0,<3"" failed with error code 1 in None
  
    ----------------------------------------
  Command "/usr/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-pu0sb232 --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- flit" failed with error code 1 in None
  
  ----------------------------------------
Command "/usr/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-9mci66_9 --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel ipython>=5 jupyter_core>=4.2 jupyter_client" failed with error code 1 in None
Failed to download ipykernel
Please fix the module manually in the generated file
```

**Comment by hfiguiere** [comment]
It did work with the current version. Maybe some other changes fixed it.
